import type { TokenIdentity } from '@zenith/types';
import { buildTokenId } from './tokenIdentity.types';
import { normalizeTokenAddress } from './addressNormalizer';
export const ZENITH_CANONICAL_TOKENS: readonly TokenIdentity[] = [
    {
        tokenId: buildTokenId('ethereum', 'NATIVE', 'ETH'),
        networkId: 'ethereum',
        networkIdentityKey: 'EVM:eip155:1',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'NATIVE',
        symbol: 'ETH',
        name: 'Ether',
        decimals: 18,
        assetType: 'NATIVE',
        isNative: true,
        isWrappedNative: false,
        wrappedAddress: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'LIVE_VERIFIED',
        capabilityLevel: 'LIVE_VERIFIED',
        onboardingState: 'LIVE_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['native', 'gas', 'layer1']
    },
    {
        tokenId: buildTokenId('ethereum', 'WRAPPED_NATIVE', '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'),
        networkId: 'ethereum',
        networkIdentityKey: 'EVM:eip155:1',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'WRAPPED_NATIVE',
        address: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
        normalizedAddress: normalizeTokenAddress('EVM', '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'),
        symbol: 'WETH',
        name: 'Wrapped Ether',
        decimals: 18,
        assetType: 'WRAPPED_NATIVE',
        isNative: false,
        isWrappedNative: true,
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'LIVE_VERIFIED',
        capabilityLevel: 'LIVE_VERIFIED',
        onboardingState: 'LIVE_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['wrapped', 'defi']
    },
    {
        tokenId: buildTokenId('ethereum', 'ERC20', '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48'),
        networkId: 'ethereum',
        networkIdentityKey: 'EVM:eip155:1',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'ERC20',
        address: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
        normalizedAddress: normalizeTokenAddress('EVM', '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48'),
        symbol: 'USDC',
        name: 'USD Coin',
        decimals: 6,
        assetType: 'FUNGIBLE_TOKEN',
        isNative: false,
        isWrappedNative: false,
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'LIVE_VERIFIED',
        capabilityLevel: 'LIVE_VERIFIED',
        onboardingState: 'LIVE_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['stablecoin', 'fiat-backed']
    },
    {
        tokenId: buildTokenId('ethereum', 'ERC20', '0xdAC17F958D2ee523a2206206994597C13D831ec7'),
        networkId: 'ethereum',
        networkIdentityKey: 'EVM:eip155:1',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'ERC20',
        address: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
        normalizedAddress: normalizeTokenAddress('EVM', '0xdAC17F958D2ee523a2206206994597C13D831ec7'),
        symbol: 'USDT',
        name: 'Tether USD',
        decimals: 6,
        assetType: 'FUNGIBLE_TOKEN',
        isNative: false,
        isWrappedNative: false,
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'LIVE_VERIFIED',
        capabilityLevel: 'LIVE_VERIFIED',
        onboardingState: 'LIVE_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['stablecoin', 'tether']
    },
    {
        tokenId: buildTokenId('ethereum', 'ERC20', '0x6B175474E89094C44Da98b954EedeAC495271d0F'),
        networkId: 'ethereum',
        networkIdentityKey: 'EVM:eip155:1',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'ERC20',
        address: '0x6B175474E89094C44Da98b954EedeAC495271d0F',
        normalizedAddress: normalizeTokenAddress('EVM', '0x6B175474E89094C44Da98b954EedeAC495271d0F'),
        symbol: 'DAI',
        name: 'Dai Stablecoin',
        decimals: 18,
        assetType: 'FUNGIBLE_TOKEN',
        isNative: false,
        isWrappedNative: false,
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'LIVE_VERIFIED',
        capabilityLevel: 'LIVE_VERIFIED',
        onboardingState: 'LIVE_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['stablecoin', 'decentralized']
    },
    {
        tokenId: buildTokenId('ethereum', 'ERC20', '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599'),
        networkId: 'ethereum',
        networkIdentityKey: 'EVM:eip155:1',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'ERC20',
        address: '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599',
        normalizedAddress: normalizeTokenAddress('EVM', '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599'),
        symbol: 'WBTC',
        name: 'Wrapped BTC',
        decimals: 8,
        assetType: 'FUNGIBLE_TOKEN',
        isNative: false,
        isWrappedNative: false,
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'LIVE_VERIFIED',
        capabilityLevel: 'LIVE_VERIFIED',
        onboardingState: 'LIVE_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['bitcoin', 'wrapped']
    },
    {
        tokenId: buildTokenId('arbitrum', 'NATIVE', 'ETH'),
        networkId: 'arbitrum',
        networkIdentityKey: 'EVM:eip155:42161',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'NATIVE',
        symbol: 'ETH',
        name: 'Ether',
        decimals: 18,
        assetType: 'NATIVE',
        isNative: true,
        isWrappedNative: false,
        wrappedAddress: '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1',
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'LIVE_VERIFIED',
        capabilityLevel: 'LIVE_VERIFIED',
        onboardingState: 'LIVE_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['native', 'gas', 'l2']
    },
    {
        tokenId: buildTokenId('arbitrum', 'WRAPPED_NATIVE', '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1'),
        networkId: 'arbitrum',
        networkIdentityKey: 'EVM:eip155:42161',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'WRAPPED_NATIVE',
        address: '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1',
        normalizedAddress: normalizeTokenAddress('EVM', '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1'),
        symbol: 'WETH',
        name: 'Wrapped Ether',
        decimals: 18,
        assetType: 'WRAPPED_NATIVE',
        isNative: false,
        isWrappedNative: true,
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'LIVE_VERIFIED',
        capabilityLevel: 'LIVE_VERIFIED',
        onboardingState: 'LIVE_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['wrapped', 'arbitrum']
    },
    {
        tokenId: buildTokenId('arbitrum', 'ERC20', '0xaf88d065e77c8cC2239327C5EDb3A432268e5831'),
        networkId: 'arbitrum',
        networkIdentityKey: 'EVM:eip155:42161',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'ERC20',
        address: '0xaf88d065e77c8cC2239327C5EDb3A432268e5831',
        normalizedAddress: normalizeTokenAddress('EVM', '0xaf88d065e77c8cC2239327C5EDb3A432268e5831'),
        symbol: 'USDC',
        name: 'USD Coin',
        decimals: 6,
        assetType: 'FUNGIBLE_TOKEN',
        isNative: false,
        isWrappedNative: false,
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'LIVE_VERIFIED',
        capabilityLevel: 'LIVE_VERIFIED',
        onboardingState: 'LIVE_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['stablecoin', 'arbitrum']
    },
    {
        tokenId: buildTokenId('arbitrum', 'ERC20', '0x912CE59144191C1204E64559FE8253a0e49E6548'),
        networkId: 'arbitrum',
        networkIdentityKey: 'EVM:eip155:42161',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'ERC20',
        address: '0x912CE59144191C1204E64559FE8253a0e49E6548',
        normalizedAddress: normalizeTokenAddress('EVM', '0x912CE59144191C1204E64559FE8253a0e49E6548'),
        symbol: 'ARB',
        name: 'Arbitrum',
        decimals: 18,
        assetType: 'FUNGIBLE_TOKEN',
        isNative: false,
        isWrappedNative: false,
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'LIVE_VERIFIED',
        capabilityLevel: 'LIVE_VERIFIED',
        onboardingState: 'LIVE_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['governance', 'arbitrum']
    },
    {
        tokenId: buildTokenId('optimism', 'NATIVE', 'ETH'),
        networkId: 'optimism',
        networkIdentityKey: 'EVM:eip155:10',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'NATIVE',
        symbol: 'ETH',
        name: 'Ether',
        decimals: 18,
        assetType: 'NATIVE',
        isNative: true,
        isWrappedNative: false,
        wrappedAddress: '0x4200000000000000000000000000000000000006',
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'LIVE_VERIFIED',
        capabilityLevel: 'LIVE_VERIFIED',
        onboardingState: 'LIVE_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['native', 'gas', 'optimism']
    },
    {
        tokenId: buildTokenId('optimism', 'WRAPPED_NATIVE', '0x4200000000000000000000000000000000000006'),
        networkId: 'optimism',
        networkIdentityKey: 'EVM:eip155:10',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'WRAPPED_NATIVE',
        address: '0x4200000000000000000000000000000000000006',
        normalizedAddress: normalizeTokenAddress('EVM', '0x4200000000000000000000000000000000000006'),
        symbol: 'WETH',
        name: 'Wrapped Ether',
        decimals: 18,
        assetType: 'WRAPPED_NATIVE',
        isNative: false,
        isWrappedNative: true,
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'LIVE_VERIFIED',
        capabilityLevel: 'LIVE_VERIFIED',
        onboardingState: 'LIVE_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['wrapped', 'optimism']
    },
    {
        tokenId: buildTokenId('optimism', 'ERC20', '0x0b3e328455c4059EEb9e3f84b5543F74E24e7E1b'),
        networkId: 'optimism',
        networkIdentityKey: 'EVM:eip155:10',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'ERC20',
        address: '0x0b3e328455c4059EEb9e3f84b5543F74E24e7E1b',
        normalizedAddress: normalizeTokenAddress('EVM', '0x0b3e328455c4059EEb9e3f84b5543F74E24e7E1b'),
        symbol: 'USDC',
        name: 'USD Coin',
        decimals: 6,
        assetType: 'FUNGIBLE_TOKEN',
        isNative: false,
        isWrappedNative: false,
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'LIVE_VERIFIED',
        capabilityLevel: 'LIVE_VERIFIED',
        onboardingState: 'LIVE_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['stablecoin', 'optimism']
    },
    {
        tokenId: buildTokenId('optimism', 'ERC20', '0x4200000000000000000000000000000000000042'),
        networkId: 'optimism',
        networkIdentityKey: 'EVM:eip155:10',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'ERC20',
        address: '0x4200000000000000000000000000000000000042',
        normalizedAddress: normalizeTokenAddress('EVM', '0x4200000000000000000000000000000000000042'),
        symbol: 'OP',
        name: 'Optimism',
        decimals: 18,
        assetType: 'FUNGIBLE_TOKEN',
        isNative: false,
        isWrappedNative: false,
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'LIVE_VERIFIED',
        capabilityLevel: 'LIVE_VERIFIED',
        onboardingState: 'LIVE_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['governance', 'optimism']
    },
    {
        tokenId: buildTokenId('base', 'NATIVE', 'ETH'),
        networkId: 'base',
        networkIdentityKey: 'EVM:eip155:8453',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'NATIVE',
        symbol: 'ETH',
        name: 'Ether',
        decimals: 18,
        assetType: 'NATIVE',
        isNative: true,
        isWrappedNative: false,
        wrappedAddress: '0x4200000000000000000000000000000000000006',
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'LIVE_VERIFIED',
        capabilityLevel: 'LIVE_VERIFIED',
        onboardingState: 'LIVE_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['native', 'gas', 'base']
    },
    {
        tokenId: buildTokenId('base', 'WRAPPED_NATIVE', '0x4200000000000000000000000000000000000006'),
        networkId: 'base',
        networkIdentityKey: 'EVM:eip155:8453',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'WRAPPED_NATIVE',
        address: '0x4200000000000000000000000000000000000006',
        normalizedAddress: normalizeTokenAddress('EVM', '0x4200000000000000000000000000000000000006'),
        symbol: 'WETH',
        name: 'Wrapped Ether',
        decimals: 18,
        assetType: 'WRAPPED_NATIVE',
        isNative: false,
        isWrappedNative: true,
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'LIVE_VERIFIED',
        capabilityLevel: 'LIVE_VERIFIED',
        onboardingState: 'LIVE_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['wrapped', 'base']
    },
    {
        tokenId: buildTokenId('base', 'ERC20', '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913'),
        networkId: 'base',
        networkIdentityKey: 'EVM:eip155:8453',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'ERC20',
        address: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
        normalizedAddress: normalizeTokenAddress('EVM', '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913'),
        symbol: 'USDC',
        name: 'USD Coin',
        decimals: 6,
        assetType: 'FUNGIBLE_TOKEN',
        isNative: false,
        isWrappedNative: false,
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'LIVE_VERIFIED',
        capabilityLevel: 'LIVE_VERIFIED',
        onboardingState: 'LIVE_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['stablecoin', 'base']
    },
    {
        tokenId: buildTokenId('polygon', 'NATIVE', 'POL'),
        networkId: 'polygon',
        networkIdentityKey: 'EVM:eip155:137',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'NATIVE',
        symbol: 'POL',
        name: 'Polygon Ecosystem Token',
        decimals: 18,
        assetType: 'NATIVE',
        isNative: true,
        isWrappedNative: false,
        wrappedAddress: '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270',
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'LIVE_VERIFIED',
        capabilityLevel: 'LIVE_VERIFIED',
        onboardingState: 'LIVE_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['native', 'gas', 'polygon']
    },
    {
        tokenId: buildTokenId('polygon', 'WRAPPED_NATIVE', '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270'),
        networkId: 'polygon',
        networkIdentityKey: 'EVM:eip155:137',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'WRAPPED_NATIVE',
        address: '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270',
        normalizedAddress: normalizeTokenAddress('EVM', '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270'),
        symbol: 'WMATIC',
        name: 'Wrapped MATIC',
        decimals: 18,
        assetType: 'WRAPPED_NATIVE',
        isNative: false,
        isWrappedNative: true,
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'LIVE_VERIFIED',
        capabilityLevel: 'LIVE_VERIFIED',
        onboardingState: 'LIVE_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['wrapped', 'polygon']
    },
    {
        tokenId: buildTokenId('polygon', 'ERC20', '0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359'),
        networkId: 'polygon',
        networkIdentityKey: 'EVM:eip155:137',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'ERC20',
        address: '0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359',
        normalizedAddress: normalizeTokenAddress('EVM', '0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359'),
        symbol: 'USDC',
        name: 'USD Coin',
        decimals: 6,
        assetType: 'FUNGIBLE_TOKEN',
        isNative: false,
        isWrappedNative: false,
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'LIVE_VERIFIED',
        capabilityLevel: 'LIVE_VERIFIED',
        onboardingState: 'LIVE_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['stablecoin', 'polygon']
    },
    {
        tokenId: buildTokenId('avalanche', 'NATIVE', 'AVAX'),
        networkId: 'avalanche',
        networkIdentityKey: 'EVM:eip155:43114',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'NATIVE',
        symbol: 'AVAX',
        name: 'Avalanche',
        decimals: 18,
        assetType: 'NATIVE',
        isNative: true,
        isWrappedNative: false,
        wrappedAddress: '0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7',
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'REGISTRY_VERIFIED',
        capabilityLevel: 'CONFIGURED',
        onboardingState: 'METADATA_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['native', 'gas', 'avalanche']
    },
    {
        tokenId: buildTokenId('avalanche', 'WRAPPED_NATIVE', '0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7'),
        networkId: 'avalanche',
        networkIdentityKey: 'EVM:eip155:43114',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'WRAPPED_NATIVE',
        address: '0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7',
        normalizedAddress: normalizeTokenAddress('EVM', '0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7'),
        symbol: 'WAVAX',
        name: 'Wrapped AVAX',
        decimals: 18,
        assetType: 'WRAPPED_NATIVE',
        isNative: false,
        isWrappedNative: true,
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'REGISTRY_VERIFIED',
        capabilityLevel: 'CONFIGURED',
        onboardingState: 'METADATA_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['wrapped', 'avalanche']
    },
    {
        tokenId: buildTokenId('bsc', 'NATIVE', 'BNB'),
        networkId: 'bsc',
        networkIdentityKey: 'EVM:eip155:56',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'NATIVE',
        symbol: 'BNB',
        name: 'BNB',
        decimals: 18,
        assetType: 'NATIVE',
        isNative: true,
        isWrappedNative: false,
        wrappedAddress: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c',
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'REGISTRY_VERIFIED',
        capabilityLevel: 'CONFIGURED',
        onboardingState: 'METADATA_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['native', 'gas', 'bsc']
    },
    {
        tokenId: buildTokenId('bsc', 'WRAPPED_NATIVE', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c'),
        networkId: 'bsc',
        networkIdentityKey: 'EVM:eip155:56',
        family: 'EVM',
        namespace: 'eip155',
        standard: 'WRAPPED_NATIVE',
        address: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c',
        normalizedAddress: normalizeTokenAddress('EVM', '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c'),
        symbol: 'WBNB',
        name: 'Wrapped BNB',
        decimals: 18,
        assetType: 'WRAPPED_NATIVE',
        isNative: false,
        isWrappedNative: true,
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'REGISTRY_VERIFIED',
        capabilityLevel: 'CONFIGURED',
        onboardingState: 'METADATA_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['wrapped', 'bsc']
    },
    {
        tokenId: buildTokenId('solana', 'NATIVE', 'SOL'),
        networkId: 'solana',
        networkIdentityKey: 'SOLANA:solana:mainnet-beta',
        family: 'SOLANA',
        namespace: 'solana',
        standard: 'NATIVE',
        symbol: 'SOL',
        name: 'Solana',
        decimals: 9,
        assetType: 'NATIVE',
        isNative: true,
        isWrappedNative: false,
        wrappedAddress: 'So11111111111111111111111111111111111111112',
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'REGISTRY_VERIFIED',
        capabilityLevel: 'CONFIGURED',
        onboardingState: 'METADATA_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['native', 'gas', 'solana']
    },
    {
        tokenId: buildTokenId('solana', 'SPL', 'So11111111111111111111111111111111111111112'),
        networkId: 'solana',
        networkIdentityKey: 'SOLANA:solana:mainnet-beta',
        family: 'SOLANA',
        namespace: 'solana',
        standard: 'SPL',
        address: 'So11111111111111111111111111111111111111112',
        normalizedAddress: normalizeTokenAddress('SOLANA', 'So11111111111111111111111111111111111111112'),
        symbol: 'WSOL',
        name: 'Wrapped SOL',
        decimals: 9,
        assetType: 'WRAPPED_NATIVE',
        isNative: false,
        isWrappedNative: true,
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'REGISTRY_VERIFIED',
        capabilityLevel: 'CONFIGURED',
        onboardingState: 'METADATA_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['spl', 'wrapped', 'solana']
    },
    {
        tokenId: buildTokenId('solana', 'SPL', 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'),
        networkId: 'solana',
        networkIdentityKey: 'SOLANA:solana:mainnet-beta',
        family: 'SOLANA',
        namespace: 'solana',
        standard: 'SPL',
        address: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
        normalizedAddress: normalizeTokenAddress('SOLANA', 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'),
        symbol: 'USDC',
        name: 'USD Coin',
        decimals: 6,
        assetType: 'FUNGIBLE_TOKEN',
        isNative: false,
        isWrappedNative: false,
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'REGISTRY_VERIFIED',
        capabilityLevel: 'CONFIGURED',
        onboardingState: 'METADATA_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['spl', 'stablecoin', 'solana']
    },
    {
        tokenId: buildTokenId('bitcoin', 'NATIVE', 'BTC'),
        networkId: 'bitcoin',
        networkIdentityKey: 'BITCOIN:bip122:bitcoin-mainnet',
        family: 'BITCOIN',
        namespace: 'bip122',
        standard: 'NATIVE',
        symbol: 'BTC',
        name: 'Bitcoin',
        decimals: 8,
        assetType: 'NATIVE',
        isNative: true,
        isWrappedNative: false,
        verificationStatus: 'IDENTITY_VERIFIED',
        verificationDimensions: {
            identityVerified: true,
            addressVerified: true,
            standardVerified: true,
            decimalsVerified: true,
            metadataVerified: true,
            contractCodeVerified: true,
            networkVerified: true
        },
        metadataStatus: 'REGISTRY_VERIFIED',
        capabilityLevel: 'CONFIGURED',
        onboardingState: 'METADATA_VERIFIED',
        source: 'CANONICAL_SEED',
        isFungible: true,
        isNFT: false,
        isMultiToken: false,
        tags: ['native', 'utxo', 'bitcoin']
    }
];
