import type { DexIdentity } from '@zenith/types';
import { buildDexIdentityKey } from './dexIdentity.types';
const RAW_CANONICAL_DEXES: readonly DexIdentity[] = [
    {
        dexId: 'ethereum:uniswap-v3',
        canonicalName: 'Uniswap V3',
        displayName: 'Uniswap V3 (Ethereum)',
        networkId: 'ethereum',
        networkIdentityKey: 'EVM:eip155:1',
        family: 'EVM',
        protocolFamily: 'UNISWAP_V3_STYLE',
        version: 'V3',
        deploymentId: 'ethereum-mainnet',
        routerAddress: '0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45',
        factoryAddress: '0x1F98431c8aD98523631AE4a59f267346ea31F984',
        quoterAddress: '0x61fFE014bA17989E743c5F6cB21bF9697530B21e',
        universalRouterAddress: '0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD',
        positionManagerAddress: '0xC36442b4a4522E871399CD717aBDD847Ab11FE88',
        poolDiscoveryMethod: 'FACTORY_LOOKUP',
        swapMethods: ['exactInputSingle', 'exactInput', 'multicall'],
        supportedTokenStandards: ['ERC20'],
        status: 'ACTIVE',
        verificationStatus: 'EXPECTED_INTERFACE',
        capabilityLevel: 'EXECUTION_AVAILABLE',
        onboardingState: 'EXECUTION_ENABLED',
        feeTiersBps: [1, 5, 30, 100],
        quoteTtlMs: 15000
    },
    {
        dexId: 'ethereum:uniswap-v2',
        canonicalName: 'Uniswap V2',
        displayName: 'Uniswap V2 (Ethereum)',
        networkId: 'ethereum',
        networkIdentityKey: 'EVM:eip155:1',
        family: 'EVM',
        protocolFamily: 'UNISWAP_V2_STYLE',
        version: 'V2',
        deploymentId: 'ethereum-mainnet',
        routerAddress: '0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D',
        factoryAddress: '0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f',
        poolDiscoveryMethod: 'FACTORY_LOOKUP',
        swapMethods: ['swapExactTokensForTokens', 'swapExactETHForTokens', 'swapExactTokensForETH'],
        supportedTokenStandards: ['ERC20'],
        status: 'ACTIVE',
        verificationStatus: 'EXPECTED_INTERFACE',
        capabilityLevel: 'EXECUTION_AVAILABLE',
        onboardingState: 'EXECUTION_ENABLED',
        feeTiersBps: [30],
        quoteTtlMs: 15000
    },
    {
        dexId: 'ethereum:pancakeswap-v3',
        canonicalName: 'PancakeSwap V3',
        displayName: 'PancakeSwap V3 (Ethereum)',
        networkId: 'ethereum',
        networkIdentityKey: 'EVM:eip155:1',
        family: 'EVM',
        protocolFamily: 'UNISWAP_V3_STYLE',
        version: 'V3',
        deploymentId: 'ethereum-mainnet',
        routerAddress: '0x13f4EA83D0bd40E75C8222255bc855a974568Dd4',
        factoryAddress: '0x0BFbCF9fa4f9C56B0F40a671Ad40E0805A091865',
        poolDiscoveryMethod: 'FACTORY_LOOKUP',
        swapMethods: ['exactInputSingle', 'exactInput'],
        supportedTokenStandards: ['ERC20'],
        status: 'ACTIVE',
        verificationStatus: 'CONTRACT_PRESENT',
        capabilityLevel: 'CONFIGURED',
        onboardingState: 'CONFIGURED',
        feeTiersBps: [1, 5, 25, 100],
        quoteTtlMs: 15000
    },
    {
        dexId: 'polygon:uniswap-v3',
        canonicalName: 'Uniswap V3',
        displayName: 'Uniswap V3 (Polygon)',
        networkId: 'polygon',
        networkIdentityKey: 'EVM:eip155:137',
        family: 'EVM',
        protocolFamily: 'UNISWAP_V3_STYLE',
        version: 'V3',
        deploymentId: 'polygon-mainnet',
        routerAddress: '0xE592427A0AEce92De3Edee1F18E0157C05861564',
        factoryAddress: '0x1F98431c8aD98523631AE4a59f267346ea31F984',
        quoterAddress: '0x61fFE014bA17989E743c5F6cB21bF9697530B21e',
        universalRouterAddress: '0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD',
        positionManagerAddress: '0xC36442b4a4522E871399CD717aBDD847Ab11FE88',
        poolDiscoveryMethod: 'FACTORY_LOOKUP',
        swapMethods: ['exactInputSingle', 'exactInput', 'multicall'],
        supportedTokenStandards: ['ERC20'],
        status: 'ACTIVE',
        verificationStatus: 'EXPECTED_INTERFACE',
        capabilityLevel: 'EXECUTION_AVAILABLE',
        onboardingState: 'EXECUTION_ENABLED',
        feeTiersBps: [1, 5, 30, 100],
        quoteTtlMs: 15000
    },
    {
        dexId: 'polygon:quickswap-v3',
        canonicalName: 'QuickSwap V3',
        displayName: 'QuickSwap V3 (Polygon)',
        networkId: 'polygon',
        networkIdentityKey: 'EVM:eip155:137',
        family: 'EVM',
        protocolFamily: 'CONCENTRATED_LIQUIDITY_AMM',
        version: 'V3',
        deploymentId: 'polygon-mainnet',
        routerAddress: '0xf5b509bB0909a69B1c207E495f687a596C168E12',
        factoryAddress: '0x411b0fAcC3489691f28ad58c47006AF5E3Ab3A28',
        poolDiscoveryMethod: 'FACTORY_LOOKUP',
        swapMethods: ['exactInputSingle', 'exactInput'],
        supportedTokenStandards: ['ERC20'],
        status: 'ACTIVE',
        verificationStatus: 'EXPECTED_INTERFACE',
        capabilityLevel: 'EXECUTION_AVAILABLE',
        onboardingState: 'EXECUTION_ENABLED',
        quoteTtlMs: 15000
    },
    {
        dexId: 'polygon:quickswap-v2',
        canonicalName: 'QuickSwap V2',
        displayName: 'QuickSwap V2 (Polygon)',
        networkId: 'polygon',
        networkIdentityKey: 'EVM:eip155:137',
        family: 'EVM',
        protocolFamily: 'UNISWAP_V2_STYLE',
        version: 'V2',
        deploymentId: 'polygon-mainnet',
        routerAddress: '0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff',
        factoryAddress: '0x5757371414417b8C6CAad45bAeF941aBc7d3Ab32',
        poolDiscoveryMethod: 'FACTORY_LOOKUP',
        swapMethods: ['swapExactTokensForTokens', 'swapExactETHForTokens', 'swapExactTokensForETH'],
        supportedTokenStandards: ['ERC20'],
        status: 'ACTIVE',
        verificationStatus: 'CONTRACT_PRESENT',
        capabilityLevel: 'CONFIGURED',
        onboardingState: 'CONFIGURED',
        quoteTtlMs: 15000
    },
    {
        dexId: 'arbitrum:uniswap-v3',
        canonicalName: 'Uniswap V3',
        displayName: 'Uniswap V3 (Arbitrum)',
        networkId: 'arbitrum',
        networkIdentityKey: 'EVM:eip155:42161',
        family: 'EVM',
        protocolFamily: 'UNISWAP_V3_STYLE',
        version: 'V3',
        deploymentId: 'arbitrum-mainnet',
        routerAddress: '0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45',
        factoryAddress: '0x1F98431c8aD98523631AE4a59f267346ea31F984',
        quoterAddress: '0x61fFE014bA17989E743c5F6cB21bF9697530B21e',
        universalRouterAddress: '0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD',
        positionManagerAddress: '0xC36442b4a4522E871399CD717aBDD847Ab11FE88',
        poolDiscoveryMethod: 'FACTORY_LOOKUP',
        swapMethods: ['exactInputSingle', 'exactInput', 'multicall'],
        supportedTokenStandards: ['ERC20'],
        status: 'ACTIVE',
        verificationStatus: 'EXPECTED_INTERFACE',
        capabilityLevel: 'EXECUTION_AVAILABLE',
        onboardingState: 'EXECUTION_ENABLED',
        feeTiersBps: [1, 5, 30, 100],
        quoteTtlMs: 15000
    },
    {
        dexId: 'arbitrum:camelot-v3',
        canonicalName: 'Camelot V3',
        displayName: 'Camelot V3 (Arbitrum)',
        networkId: 'arbitrum',
        networkIdentityKey: 'EVM:eip155:42161',
        family: 'EVM',
        protocolFamily: 'CONCENTRATED_LIQUIDITY_AMM',
        version: 'V3',
        deploymentId: 'arbitrum-mainnet',
        routerAddress: '0x1F721E2E82F6676FCE4eA07A5958cF098D339e18',
        factoryAddress: '0x521aa84c16204c2ae704b291e9ab13eb224c168d',
        poolDiscoveryMethod: 'FACTORY_LOOKUP',
        swapMethods: ['exactInputSingle', 'exactInput'],
        supportedTokenStandards: ['ERC20'],
        status: 'ACTIVE',
        verificationStatus: 'CONTRACT_PRESENT',
        capabilityLevel: 'CONFIGURED',
        onboardingState: 'CONFIGURED',
        quoteTtlMs: 15000
    },
    {
        dexId: 'arbitrum:camelot-v2',
        canonicalName: 'Camelot V2',
        displayName: 'Camelot V2 (Arbitrum)',
        networkId: 'arbitrum',
        networkIdentityKey: 'EVM:eip155:42161',
        family: 'EVM',
        protocolFamily: 'UNISWAP_V2_STYLE',
        version: 'V2',
        deploymentId: 'arbitrum-mainnet',
        routerAddress: '0xc873fEcbd354f5A56E00E710B90EF4201db2448d',
        factoryAddress: '0x6EcCab422D763aC031210895C81787E87B432c51',
        poolDiscoveryMethod: 'FACTORY_LOOKUP',
        swapMethods: ['swapExactTokensForTokensSupportingFeeOnTransferTokens', 'getAmountsOut'],
        supportedTokenStandards: ['ERC20'],
        status: 'ACTIVE',
        verificationStatus: 'CONTRACT_PRESENT',
        capabilityLevel: 'CONFIGURED',
        onboardingState: 'CONFIGURED',
        quoteTtlMs: 15000
    },
    {
        dexId: 'optimism:uniswap-v3',
        canonicalName: 'Uniswap V3',
        displayName: 'Uniswap V3 (Optimism)',
        networkId: 'optimism',
        networkIdentityKey: 'EVM:eip155:10',
        family: 'EVM',
        protocolFamily: 'UNISWAP_V3_STYLE',
        version: 'V3',
        deploymentId: 'optimism-mainnet',
        routerAddress: '0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45',
        factoryAddress: '0x1F98431c8aD98523631AE4a59f267346ea31F984',
        quoterAddress: '0x61fFE014bA17989E743c5F6cB21bF9697530B21e',
        universalRouterAddress: '0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD',
        positionManagerAddress: '0xC36442b4a4522E871399CD717aBDD847Ab11FE88',
        poolDiscoveryMethod: 'FACTORY_LOOKUP',
        swapMethods: ['exactInputSingle', 'exactInput', 'multicall'],
        supportedTokenStandards: ['ERC20'],
        status: 'ACTIVE',
        verificationStatus: 'EXPECTED_INTERFACE',
        capabilityLevel: 'EXECUTION_AVAILABLE',
        onboardingState: 'EXECUTION_ENABLED',
        feeTiersBps: [1, 5, 30, 100],
        quoteTtlMs: 15000
    },
    {
        dexId: 'optimism:velodrome-v2',
        canonicalName: 'Velodrome V2',
        displayName: 'Velodrome V2 (Optimism)',
        networkId: 'optimism',
        networkIdentityKey: 'EVM:eip155:10',
        family: 'EVM',
        protocolFamily: 'CONSTANT_PRODUCT_AMM',
        version: 'V2',
        deploymentId: 'optimism-mainnet',
        routerAddress: '0xa062aE8A9c5e11aaA026fc2670B0D65cCc8B2858',
        factoryAddress: '0x25CbdDb98b35ab1FF77413456B31EC81A6B6B746',
        poolDiscoveryMethod: 'FACTORY_LOOKUP',
        swapMethods: ['swapExactTokensForTokens', 'swapExactETHForTokens', 'swapExactTokensForETH'],
        supportedTokenStandards: ['ERC20'],
        status: 'ACTIVE',
        verificationStatus: 'CONTRACT_PRESENT',
        capabilityLevel: 'CONFIGURED',
        onboardingState: 'CONFIGURED',
        quoteTtlMs: 15000
    },
    {
        dexId: 'base:uniswap-v3',
        canonicalName: 'Uniswap V3',
        displayName: 'Uniswap V3 (Base)',
        networkId: 'base',
        networkIdentityKey: 'EVM:eip155:8453',
        family: 'EVM',
        protocolFamily: 'UNISWAP_V3_STYLE',
        version: 'V3',
        deploymentId: 'base-mainnet',
        routerAddress: '0x2626664c2603336E57B271c5C0b26F421741e481',
        factoryAddress: '0x33128a8fC17869897dcE68Ed026d694621f6FDfD',
        quoterAddress: '0x3d4e44Eb1374240CE5F1B871ab261CD16335B76a',
        universalRouterAddress: '0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD',
        positionManagerAddress: '0x03a520b32C04BF3bEEf7BEb72E919cf822Ed34f1',
        poolDiscoveryMethod: 'FACTORY_LOOKUP',
        swapMethods: ['exactInputSingle', 'exactInput'],
        supportedTokenStandards: ['ERC20'],
        status: 'ACTIVE',
        verificationStatus: 'EXPECTED_INTERFACE',
        capabilityLevel: 'EXECUTION_AVAILABLE',
        onboardingState: 'EXECUTION_ENABLED',
        feeTiersBps: [1, 5, 30, 100],
        quoteTtlMs: 15000
    },
    {
        dexId: 'base:aerodrome-v2',
        canonicalName: 'Aerodrome',
        displayName: 'Aerodrome (Base)',
        networkId: 'base',
        networkIdentityKey: 'EVM:eip155:8453',
        family: 'EVM',
        protocolFamily: 'CONSTANT_PRODUCT_AMM',
        version: 'V2',
        deploymentId: 'base-mainnet',
        routerAddress: '0xcF77a3Ba9A5CA399B7c97c74856154990ED379bC',
        factoryAddress: '0x420DD381b31aEf6683db6B902084cB0FFECe40Da',
        poolDiscoveryMethod: 'FACTORY_LOOKUP',
        swapMethods: ['swapExactTokensForTokens', 'swapExactETHForTokens', 'swapExactTokensForETH'],
        supportedTokenStandards: ['ERC20'],
        status: 'ACTIVE',
        verificationStatus: 'CONTRACT_PRESENT',
        capabilityLevel: 'CONFIGURED',
        onboardingState: 'CONFIGURED',
        quoteTtlMs: 15000
    },
    {
        dexId: 'bsc:pancakeswap-v3',
        canonicalName: 'PancakeSwap V3',
        displayName: 'PancakeSwap V3 (BSC)',
        networkId: 'bsc',
        networkIdentityKey: 'EVM:eip155:56',
        family: 'EVM',
        protocolFamily: 'UNISWAP_V3_STYLE',
        version: 'V3',
        deploymentId: 'bsc-mainnet',
        routerAddress: '0x13f4EA83D0bd40E75C8222255bc855a974568Dd4',
        factoryAddress: '0x0BFbCF9fa4f9C56B0F40a671Ad40E0805A091865',
        quoterAddress: '0x78D78E420dA98AD378D7799bE8f241d19F297614',
        poolDiscoveryMethod: 'FACTORY_LOOKUP',
        swapMethods: ['exactInputSingle', 'exactInput'],
        supportedTokenStandards: ['ERC20'],
        status: 'ACTIVE',
        verificationStatus: 'CONTRACT_PRESENT',
        capabilityLevel: 'CONFIGURED',
        onboardingState: 'CONFIGURED',
        feeTiersBps: [1, 5, 25, 100],
        quoteTtlMs: 15000
    },
    {
        dexId: 'avalanche:traderjoe-v2',
        canonicalName: 'Trader Joe LB',
        displayName: 'Trader Joe Liquidity Book (Avalanche)',
        networkId: 'avalanche',
        networkIdentityKey: 'EVM:eip155:43114',
        family: 'EVM',
        protocolFamily: 'CONCENTRATED_LIQUIDITY_AMM',
        version: 'V2.1',
        deploymentId: 'avalanche-mainnet',
        routerAddress: '0xB4310e7de3e0f14172488457B1a97140ecc94B77',
        factoryAddress: '0x8e42f2F4101563bF679975178e880FD87d3eFd4e',
        poolDiscoveryMethod: 'FACTORY_LOOKUP',
        swapMethods: ['swapExactTokensForTokens', 'swapExactNATIVEForTokens', 'swapExactTokensForNATIVE'],
        supportedTokenStandards: ['ERC20'],
        status: 'ACTIVE',
        verificationStatus: 'CONTRACT_PRESENT',
        capabilityLevel: 'CONFIGURED',
        onboardingState: 'CONFIGURED',
        quoteTtlMs: 15000
    },
    {
        dexId: 'anvil:zenith-v3',
        canonicalName: 'ZENITH V3',
        displayName: 'ZENITH V3 Concentrated AMM (Anvil)',
        networkId: 'anvil',
        networkIdentityKey: 'EVM:eip155:31337',
        family: 'EVM',
        protocolFamily: 'CONCENTRATED_LIQUIDITY_AMM',
        version: 'V3',
        deploymentId: 'anvil-local-devnet',
        routerAddress: '0x976EA74026E726554dB657fA54763abd0C3a0aa9',
        factoryAddress: '0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc',
        positionManagerAddress: '0x14dC79964da2C08b23698B3D3cc7Ca32193d9955',
        poolDiscoveryMethod: 'FACTORY_LOOKUP',
        swapMethods: ['exactInputSingle', 'multicall'],
        supportedTokenStandards: ['ERC20'],
        status: 'ACTIVE',
        verificationStatus: 'VERIFIED_DEPLOYMENT',
        capabilityLevel: 'EXECUTION_AVAILABLE',
        onboardingState: 'EXECUTION_ENABLED',
        feeTiersBps: [5, 30, 100],
        quoteTtlMs: 60000
    },
    {
        dexId: 'anvil:zenith-v2',
        canonicalName: 'ZENITH V2',
        displayName: 'ZENITH V2 AMM (Anvil)',
        networkId: 'anvil',
        networkIdentityKey: 'EVM:eip155:31337',
        family: 'EVM',
        protocolFamily: 'CONSTANT_PRODUCT_AMM',
        version: 'V2',
        deploymentId: 'anvil-local-devnet',
        routerAddress: '0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65',
        factoryAddress: '0x90F79bf6EB2c4f870365E785982E1f101E93b906',
        poolDiscoveryMethod: 'FACTORY_LOOKUP',
        swapMethods: ['swapExactTokensForTokens'],
        supportedTokenStandards: ['ERC20'],
        status: 'ACTIVE',
        verificationStatus: 'VERIFIED_DEPLOYMENT',
        capabilityLevel: 'EXECUTION_AVAILABLE',
        onboardingState: 'EXECUTION_ENABLED',
        quoteTtlMs: 60000
    },
    {
        dexId: 'anvil:zenith-v1',
        canonicalName: 'ZENITH V1',
        displayName: 'ZENITH V1 AMM (Anvil)',
        networkId: 'anvil',
        networkIdentityKey: 'EVM:eip155:31337',
        family: 'EVM',
        protocolFamily: 'CONSTANT_PRODUCT_AMM',
        version: 'V1',
        deploymentId: 'anvil-local-devnet',
        routerAddress: '0x89205A3A3b2A69De6Dbf7f01ED13B2108B2c43e7',
        factoryAddress: '0x71C84167B3aFdae37c4FEdf64082269c4c478a22',
        poolDiscoveryMethod: 'FACTORY_LOOKUP',
        swapMethods: ['swapExactTokensForTokens'],
        supportedTokenStandards: ['ERC20'],
        status: 'ACTIVE',
        verificationStatus: 'VERIFIED_DEPLOYMENT',
        capabilityLevel: 'EXECUTION_AVAILABLE',
        onboardingState: 'EXECUTION_ENABLED',
        quoteTtlMs: 60000
    },
    {
        dexId: 'solana:raydium',
        canonicalName: 'Raydium AMM V4',
        displayName: 'Raydium AMM V4 (Solana)',
        networkId: 'solana',
        networkIdentityKey: 'SOLANA:solana:mainnet-beta',
        family: 'SOLANA',
        protocolFamily: 'CONSTANT_PRODUCT_AMM',
        version: 'V4',
        deploymentId: 'solana-mainnet',
        routerAddress: '675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8',
        factoryAddress: '675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8',
        poolDiscoveryMethod: 'SUBGRAPH_INDEXER',
        swapMethods: ['swap'],
        supportedTokenStandards: ['SPL'],
        status: 'ACTIVE',
        verificationStatus: 'UNVERIFIED',
        capabilityLevel: 'CONFIGURED',
        onboardingState: 'CONFIGURED',
        quoteTtlMs: 15000
    }
];
function extractProtocolFromDex(dex: Omit<DexIdentity, 'identityKey'>): string {
    if (dex.canonicalName.startsWith('Trader Joe'))
        return 'TRADERJOE';
    return dex.canonicalName.split(' ')[0].toUpperCase();
}
export const CANONICAL_DEXES: readonly DexIdentity[] = RAW_CANONICAL_DEXES.map((dex) => ({
    ...dex,
    identityKey: dex.identityKey || buildDexIdentityKey(dex.networkIdentityKey, extractProtocolFromDex(dex), dex.version, dex.deploymentId)
}));
export const CANONICAL_DEX_DEFINITIONS = CANONICAL_DEXES;
